package com.anis.larp.ui.theme

import androidx.compose.ui.graphics.Color

internal val PurplePrimaryLight = Color(0xFF6D4BC3)
internal val OnPurplePrimaryLight = Color(0xFFFFFFFF)
internal val PurpleContainerLight = Color(0xFFE9DDFF)
internal val OnPurpleContainerLight = Color(0xFF24105A)
internal val BlueSecondaryLight = Color(0xFF3E608F)
internal val OnBlueSecondaryLight = Color(0xFFFFFFFF)
internal val BlueContainerLight = Color(0xFFD6E3FF)
internal val OnBlueContainerLight = Color(0xFF071C38)
internal val GreenTertiaryLight = Color(0xFF3D6751)
internal val OnGreenTertiaryLight = Color(0xFFFFFFFF)
internal val GreenContainerLight = Color(0xFFBFECCE)
internal val OnGreenContainerLight = Color(0xFF002113)
internal val ErrorLight = Color(0xFFBA1A1A)
internal val BackgroundLight = Color(0xFFFFF8F5)
internal val OnBackgroundLight = Color(0xFF1E1A1D)
internal val SurfaceLight = Color(0xFFFFF8F5)
internal val SurfaceVariantLight = Color(0xFFE9E0E8)
internal val OutlineLight = Color(0xFF7A747D)
internal val OutlineVariantLight = Color(0xFFCBC3CC)

internal val PurplePrimaryDark = Color(0xFFD0BCFF)
internal val OnPurplePrimaryDark = Color(0xFF3C1F78)
internal val PurpleContainerDark = Color(0xFF54359B)
internal val OnPurpleContainerDark = Color(0xFFE9DDFF)
internal val BlueSecondaryDark = Color(0xFFA8C8FB)
internal val OnBlueSecondaryDark = Color(0xFF0B305F)
internal val BlueContainerDark = Color(0xFF254876)
internal val OnBlueContainerDark = Color(0xFFD6E3FF)
internal val GreenTertiaryDark = Color(0xFFA4D0B3)
internal val OnGreenTertiaryDark = Color(0xFF0D3825)
internal val GreenContainerDark = Color(0xFF254F3A)
internal val OnGreenContainerDark = Color(0xFFBFECCE)
internal val ErrorDark = Color(0xFFFFB4AB)
internal val BackgroundDark = Color(0xFF161217)
internal val OnBackgroundDark = Color(0xFFE9E0E6)
internal val SurfaceDark = Color(0xFF161217)
internal val SurfaceVariantDark = Color(0xFF49454D)
internal val OutlineDark = Color(0xFF958E98)
internal val OutlineVariantDark = Color(0xFF49454D)
